ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    use_sim_time: true
    sensor_timeout: 0.1
    two_d_mode: true

    # Sensor configurations (wheel odometry + IMU)
    odom0: /odom_wheels
    odom0_config: [true, true, false,  # x, y (from wheel encoders)
                  false, false, false,  # No orientation from wheels
                  false, false, false,
                  false, false, false,
                  false, false, false]
    odom0_differential: false

    imu0: /imu_base  # IMU topic
    imu0_config: [false, false, false,  # No position
                  false, false, true,   # Fuse yaw (orientation)
                  false, false, false,
                  false, false, true,   # Fuse angular velocity (z-axis)
                  true, true, true]     # Fuse linear acceleration
    imu0_remove_gravitational_acceleration: true

    # TF settings
    publish_tf: true
    # map_frame: map
    odom_frame: odom
    # base_link_frame: base_link
    base_link_frame: base_footprint
    world_frame: odom