ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    use_sim_time: true
    sensor_timeout: 0.1
    two_d_mode: true

    # Sensor configurations (wheel odometry + IMU)
    odom0: /odom_wheels
    # x, y, z, 
    # roll, pitch, yaw,
    # vx, vy, vz, 
    # vroll, vpitch, vyaw,
    # ax, ay, az 
    odom0_config: [true,  true,  false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]

    odom0_differential: false

    imu0: /imu_base  # IMU topic
    imu0_config: [false, false, false,
                  true,  true, true,
                  false, false, false,
                  true,  true,  true,
                  false,  false,  false]
    imu0_remove_gravitational_acceleration: true

    # TF settings
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom