amcl:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    global_frame_id: "map"
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    initial_pose:
      x: 0.0
      y: 0.0
      yaw: 0.0

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "map.yaml"  # Path relative to map directory

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    min_x_velocity: -0.5
    max_x_velocity: 0.5
    min_theta_velocity: -1.0
    max_theta_velocity: 1.0
    tolerance: 0.25
    lookahead_distance: 0.3

planner_server:
  ros__parameters:
    use_sim_time: True
    planner_plugin_types: ["nav2_navfn_planner/NavfnPlanner"]
    planner_plugin_ids: ["GridBased"]

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      global_frame: odom
      robot_base_frame: base_footprint
      width: 3.0
      height: 3.0
      resolution: 0.05
      plugins: 
        - name: voxel_layer
          type: "nav2_costmap_2d::VoxelLayer" 
        - name: inflation_layer
          type: "nav2_costmap_2d::InflationLayer"
      inflation_layer:
        enabled: True
        inflation_radius: 0.55
      voxel_layer:
        enabled: True
        origin_z: 0.0
        z_resolution: 0.2
        z_voxels: 2
        unknown_threshold: 15
        mark_threshold: 0


global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: True
      global_frame: map
      robot_base_frame: base_footprint
      width: 10.0
      height: 10.0
      resolution: 0.05
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        map_subscribe_transient_local: True
      obstacle_layer:
        observation_sources: scan
        scan:
          topic: /scan
          data_type: LaserScan
          marking: True
          clearing: True
      inflation_layer:
        inflation_radius: 0.55

behavior_server:
  ros__parameters:
    use_sim_time: True
    local_frame: odom
    global_frame: map

bt_navigator:
  ros__parameters:
    use_sim_time: True
    plugin_lib_names:
      - "nav2_compute_path_to_pose_action_bt_node"
      - "nav2_follow_path_action_bt_node"
      - "nav2_back_up_action_bt_node"
      - "nav2_spin_action_bt_node"
      - "nav2_wait_action_bt_node"
      - "nav2_clear_costmap_service_bt_node"

lifecycle_manager_localization:
  ros__parameters:
    use_sim_time: True
    node_names:
      - map_server
      - amcl

lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: True
    node_names:
      - controller_server
      - planner_server
      - behavior_server
      - bt_navigator
      - global_costmap/global_costmap
      - local_costmap/local_costmap