slam_toolbox:
  ros__parameters:
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: scan  # Matches your LIDAR's topic
    mode: mapping
    use_sim_time: true  # Critical for Gazebo simulation