<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <link name="base_footprint" />

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 -${0.1458 + 0.025}" rpy="0 0 0"/>
      <geometry>
        <!-- <mesh filename="file:///$(find bb8_description)/meshes/frame_b.stl" scale="0.000995 0.000995 0.000995"/> -->
        <cylinder length="0.05" radius="0.09" />
      </geometry>
      <material name="blue"/>
    </visual>
    <!-- No need for collision -->
    <!-- <collision>
      <geometry>
        <mesh filename="file:///$(find bb8_description)/meshes/frame_b.stl" scale="0.000995 0.000995 0.000995"/>
      </geometry>
    </collision> -->
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.1" iyy="0.1" izz="0.1" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <link name="counterweight">
    <visual>
      <!-- STL origin is messed up, so need to move it -->
      <origin xyz="0 0 ${0.19+0.05}" rpy="0 0 0"/> 
      <geometry>
        <mesh filename="file:///$(find bb8_description)/meshes/counterweight.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <mass value="3.0"/>
      <inertia ixx="1.0" iyy="1.0" izz="1.0" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>


  <!-- Left Wheel Link -->
  <link name="left_wheel">
    <visual>
      <geometry>
        <mesh filename="file:///$(find bb8_description)/meshes/wheel.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="file:///$(find bb8_description)/meshes/wheel.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <!-- Right Wheel Link -->
  <link name="right_wheel">
    <visual>
      <geometry>
        <mesh filename="file:///$(find bb8_description)/meshes/wheel.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="file:///$(find bb8_description)/meshes/wheel.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <!-- Joints -->
  <joint name="base_joint" type="fixed">
      <parent link="base_footprint" />
      <child link="base_link" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <joint name="counterweight_joint" type="fixed">
      <parent link="base_link" />
      <child link="counterweight" />
      <origin xyz="0 0 -${0.19+0.05}" rpy="0 0 0"/>
  </joint>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="${0.3437/2} 0 -0.1458" rpy="0 ${pi / 2} 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="-${0.3437/2} 0 -0.1458" rpy="0 ${pi/2} 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- Gazebo Plugins -->
  <gazebo>
  <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
    <update_rate>50</update_rate>
    <left_joint>left_wheel_joint</left_joint>
    <right_joint>right_wheel_joint</right_joint>
    <wheel_separation>${wheel_separation}</wheel_separation>
    <wheel_diameter>${wheel_radius * 2}"</wheel_diameter>
    <publish_odom>true</publish_odom>
    <publish_odom_tf>true</publish_odom_tf>
    <publish_wheel_tf>true</publish_wheel_tf>
    <odometry_topic>odom</odometry_topic>
    <odometry_frame>odom</odometry_frame>
    <robot_base_frame>base_footprint</robot_base_frame>
  </plugin>
  </gazebo>

  <!-- Collision Tuning for Robot and Sphere -->
  <gazebo reference="left_wheel">
    <surface>
      <contact>
        <collide_without_contact>false</collide_without_contact>
        <stiffness>1e6</stiffness>
        <damping>2e3</damping>
      </contact>
      <friction>
        <ode>
          <mu>1.0</mu> 
          <mu2>1.0</mu2>
        </ode>
      </friction>
    </surface>
  </gazebo>

  <gazebo reference="right_wheel">
    <surface>
      <contact>
        <collide_without_contact>false</collide_without_contact>
        <stiffness>1e6</stiffness>
        <damping>2e3</damping>
      </contact>
      <friction>
        <ode>
          <mu>1.0</mu> 
          <mu2>1.0</mu2>
        </ode>
      </friction>
    </surface>
  </gazebo>

</robot>